# Generated by Django 5.2.3 on 2025-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
