# Generated by Django 5.2.3 on 2025-09-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_contactmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-created_at"]},
        ),
    ]
